[package]
name = "neoark"
version = "0.1.0"
authors = ["champii <contact@champii>"]
edition = "2018"

[dependencies]
serde = ""
chrono=""
serde_derive = ""
diesel = { version = "1.4.0", features = ["postgres", "numeric"] }
serde_json = "1.0"
diesel-derive-enum = { version = "0.4.4", features = ["postgres"] }
bigdecimal = { version = "0.0.14", features = ["serde"] }
orm_macro_derive = { git = "https://gitlab.com/Champii1/diesel-orm.git" }
